services:
  - type: web
    name: familia-calendario-demo
    env: python
    region: oregon
    branch: main
    buildCommand: >
      pip install -r requirements.txt && \
      python manage.py migrate --noinput && \
      python manage.py collectstatic --noinput
    startCommand: >
      bash -lc "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python scripts/create_demo.py && gunicorn hogar.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "REPLACE_ME"
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
    autoDeploy: true

  - type: postgres
    name: familia-calendario-db
    plan: free
