# Generated by Django 4.2.14 on 2025-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
