# Generated by Django 4.2.14 on 2025-09-17 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0002_miembro_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={},
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='puntos',
            new_name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='miembro',
        ),
        migrations.AddField(
            model_name='tarea',
            name='color',
            field=models.CharField(default='#888888', max_length=7),
        ),
        migrations.AddField(
            model_name='tarea',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada por miembro'), ('aprobada', 'Aprobada por administrador')], default='pendiente', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tareas.miembro')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tareas.tarea')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.categoria'),
        ),
    ]
