# Generated by Django 4.2.14 on 2025-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tarea_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tiempo_estimado',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo estimado en minutos'),
        ),
    ]
