# Generated by Django 4.2.14 on 2025-09-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_tarea_tiempo_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='color',
        ),
    ]
