# Generated by Django 4.2.14 on 2025-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_remove_tarea_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='premio',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Premio en euros (ejemplo: 0.20)', max_digits=6),
        ),
    ]
