# Generated by Django 4.2.14 on 2025-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_tarea_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='recurrencia_dia_mes',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurrencia_dias',
            field=models.CharField(blank=True, help_text='Días de la semana separados por coma (ej: 0,2,4)', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurrencia_fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin de la recurrencia', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurrencia_fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la recurrencia', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurrencia_mes',
            field=models.PositiveIntegerField(blank=True, help_text='Mes (1-12, solo anual)', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurrencia_tipo',
            field=models.CharField(choices=[('none', 'Sin repetición'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], default='none', max_length=10),
        ),
    ]
