# Generated by Django 4.2.14 on 2025-09-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_tarea_recurrencia_dia_mes_tarea_recurrencia_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('premio', models.DecimalField(decimal_places=2, default=0.1, help_text='Premio en euros', max_digits=6)),
                ('icono', models.CharField(blank=True, default='', max_length=20)),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('marcas', 'Con marcas a conseguir')], default='simple', max_length=10)),
                ('marcas_objetivo', models.PositiveIntegerField(blank=True, help_text='Número de marcas a conseguir (solo si tipo=marcas)', null=True)),
                ('es_auto_reto', models.BooleanField(default=False, help_text='¿Es un reto a sí mismo?')),
                ('penalizacion', models.CharField(blank=True, help_text='Qué debe pagar o hacer si pierde o no cumple el reto', max_length=200)),
                ('retado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_recibidos', to='tareas.miembro')),
                ('retador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_creados', to='tareas.miembro')),
            ],
        ),
    ]
