# Generated by Django 4.2.14 on 2025-09-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_reto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
