# Generated by Django 5.2.6 on 2025-09-23 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_reto_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='reto',
            name='estado',
        ),
        migrations.AddField(
            model_name='reto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos', to='tareas.categoria'),
        ),
        migrations.AddField(
            model_name='reto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reto',
            name='puntuacion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reto',
            name='recurrencia_dia_mes',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='recurrencia_dias',
            field=models.CharField(blank=True, help_text='Días de la semana separados por coma (ej: 0,2,4)', max_length=20),
        ),
        migrations.AddField(
            model_name='reto',
            name='recurrencia_fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin de la recurrencia', null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='recurrencia_fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la recurrencia', null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='recurrencia_mes',
            field=models.PositiveIntegerField(blank=True, help_text='Mes (1-12, solo anual)', null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='recurrencia_tipo',
            field=models.CharField(choices=[('none', 'Sin repetición'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], default='none', help_text='Tipo de recurrencia', max_length=10),
        ),
        migrations.AddField(
            model_name='reto',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reto',
            name='tiempo_estimado',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo estimado en minutos'),
        ),
        migrations.AlterField(
            model_name='reto',
            name='es_auto_reto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reto',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reto',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reto',
            name='marcas_objetivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reto',
            name='penalizacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalización en euros si no se cumple el reto', max_digits=6),
        ),
        migrations.AlterField(
            model_name='reto',
            name='premio',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Premio en euros (ejemplo: 0.20)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='reto',
            name='retador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_propuestos', to='tareas.miembro'),
        ),
        migrations.AlterField(
            model_name='reto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
