# Generated by Django 5.2.6 on 2025-09-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_remove_categoria_icono_remove_reto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
