# Generated by Copilot on 2025-09-26
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0012_reto_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="reto",
            name="es_privado",
            field=models.BooleanField(default=False, help_text="Si está activo, el reto solo será visible para el retador y el retado."),
        ),
    ]
