# Generated by GitHub Copilot on 2025-09-26
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("tareas", "0012_reto_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="reto",
            name="fecha_conseguido",
            field=models.DateField(null=True, blank=True, help_text="Fecha en la que se marcó como conseguido"),
        ),
        migrations.AlterField(
            model_name="reto",
            name="estado",
            field=models.CharField(max_length=20, choices=[
                ("pendiente", "Pendiente de validación"),
                ("aprobado", "Aprobado"),
                ("rechazado", "Rechazado"),
                ("conseguido", "Conseguido"),
            ], default="pendiente"),
        ),
    ]
