# Generated by Django 5.2.6 on 2025-09-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_aviso'),
        ('tareas', '0013_reto_conseguido'),
    ]

    operations = [
    ]
