# Generated by Django 5.2.6 on 2025-09-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_reto_es_privado'),
        ('tareas', '0014_merge_0013_aviso_0013_reto_conseguido'),
    ]

    operations = [
    ]
