# Generated by Django 5.2.6 on 2025-09-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0015_merge_20250926_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='retado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retos_recibidos', to='tareas.miembro'),
        ),
    ]
