# Generated by Django 4.2.14 on 2025-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0016_alter_reto_retado'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='puntos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos acumulados por retos'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo acumulado en euros por retos', max_digits=8),
        ),
    ]
