# Generated by Django 5.2.7 on 2025-10-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0017_miembro_puntos_miembro_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='saldo',
        ),
        migrations.DeleteModel(
            name='Reto',
        ),
    ]
